
import Estructuras.ListaCurso;
import Estructuras.ListaSemestre;
import javax.swing.DefaultComboBoxModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Ushi
 */
public class Estudiante extends javax.swing.JFrame {

    ListaSemestre semestre = new ListaSemestre();
    //static Administrador admin = new Administrador();

    int Indice_Semestre = -1;
    int Indice_Curso = -1;

    /**
     * Creates new form Estudiante
     */
    public Estudiante() {
        DefaultComboBoxModel cbmodelo = new DefaultComboBoxModel();
        DefaultComboBoxModel cbmodelo2 = new DefaultComboBoxModel();
        //cbmodelo.removeAllElements();
        for (int i = 0; i < Administrador.lista_semestre.tamaño(); i++) {
            cbmodelo.addElement(Administrador.lista_semestre.obtenerNombreL(i));
        }
        for (int i = 0; i < Administrador.lista_curso.tamaño(); i++) {
            cbmodelo2.addElement(Administrador.lista_curso.obtenerNombreL(i));
        }
        initComponents();
        lblusuario.setText(Administrador.lista_estudiante.buscarCarneS(Login.UsuEstudiante));
        cbsemestre.setModel(cbmodelo);
        cbcurso.setModel(cbmodelo2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bsalir = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lblusuario = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cbsemestre = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        cbcurso = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        basignar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bsalir.setText("Salir");
        bsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bsalirActionPerformed(evt);
            }
        });

        lblusuario.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblusuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setText("Bienvenido");

        jLabel2.setText("Elija Semestre:");

        cbsemestre.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel3.setText("Seleccione el Curso:");

        cbcurso.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Codigo", "Nombre", "Catedratico", "Creditos", "Seccion"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTable1);

        basignar.setText("Asignar");
        basignar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                basignarActionPerformed(evt);
            }
        });

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addComponent(cbsemestre, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cbcurso, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(92, 92, 92))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 476, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)
                        .addGap(103, 103, 103)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblusuario, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton1))
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(207, 207, 207)
                        .addComponent(basignar)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblusuario, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbsemestre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbcurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(basignar)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(bsalir))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bsalir)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bsalirActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new Login().setVisible(true);
        int Indice_Estudiante = Administrador.lista_estudiante.obtenerIndice(Login.UsuEstudiante);
        Administrador.lista_estudiante.modificar(Indice_Estudiante, Administrador.lista_estudiante.obtenerCarneL(Indice_Estudiante), Administrador.lista_estudiante.obtenerCuiL(Indice_Estudiante), Administrador.lista_estudiante.obtenerNombreL(Indice_Estudiante), Administrador.lista_estudiante.obtenerCorreoL(Indice_Estudiante), Administrador.lista_estudiante.obtenerCreditoL(Indice_Estudiante), Administrador.lista_estudiante.obtenerContraseñaL(Indice_Estudiante), semestre);
        ListaSemestre estudiantesemestres = Administrador.lista_estudiante.obtenerSemestreL(Indice_Estudiante);
        System.out.println(Administrador.lista_estudiante.obtenerCarneL(Indice_Estudiante) + " - " + Administrador.lista_estudiante.obtenerNombreL(Indice_Estudiante));
        estudiantesemestres.imprimir();
    }//GEN-LAST:event_bsalirActionPerformed

    private void basignarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_basignarActionPerformed
        // TODO add your handling code here:
        Indice_Semestre = cbsemestre.getSelectedIndex();
        Indice_Curso = cbcurso.getSelectedIndex();
        ListaCurso cursos = new ListaCurso();
        /*for (int i = 0; i < semestre.tamaño(); i++) {
            cursos = semestre.obtenerCurso(i);
        }*/
        cursos.addPrimero(Administrador.lista_curso.obtenerCodigoL(Indice_Curso), Administrador.lista_curso.obtenerNombreL(Indice_Curso), Administrador.lista_curso.obtenerCuiL(Indice_Curso), Administrador.lista_curso.obtenerCreditoL(Indice_Curso), Administrador.lista_curso.obtenerSeccionL(Indice_Curso), Administrador.lista_curso.obtenerPreL(Indice_Curso), Administrador.lista_curso.obtenerPostL(Indice_Curso));
        if (!semestre.buscar(Administrador.lista_semestre.obtenerNombreL(Indice_Semestre))) {
            semestre.addPrimero(Administrador.lista_semestre.obtenerNombreL(Indice_Semestre), Administrador.lista_semestre.obtenerAñoL(Indice_Semestre), cursos);
        } else if (semestre.buscar(Administrador.lista_semestre.obtenerNombreL(Indice_Semestre))) {
            cursos = semestre.obtenerCurso(semestre.obtenerIndice(Administrador.lista_semestre.obtenerNombreL(Indice_Semestre)));
            cursos.addPrimero(Administrador.lista_curso.obtenerCodigoL(Indice_Curso), Administrador.lista_curso.obtenerNombreL(Indice_Curso), Administrador.lista_curso.obtenerCuiL(Indice_Curso), Administrador.lista_curso.obtenerCreditoL(Indice_Curso), Administrador.lista_curso.obtenerSeccionL(Indice_Curso), Administrador.lista_curso.obtenerPreL(Indice_Curso), Administrador.lista_curso.obtenerPostL(Indice_Curso));
            semestre.modificar(semestre.obtenerIndice(Administrador.lista_semestre.obtenerNombreL(Indice_Semestre)), Administrador.lista_semestre.obtenerNombreL(Indice_Semestre), Administrador.lista_semestre.obtenerAñoL(Indice_Semestre), cursos);
        }
        int Indice_Estudiante = Administrador.lista_estudiante.obtenerIndice(Login.UsuEstudiante);
        Administrador.lista_estudiante.modificar(Indice_Estudiante, Administrador.lista_estudiante.obtenerCarneL(Indice_Estudiante), Administrador.lista_estudiante.obtenerCuiL(Indice_Estudiante), Administrador.lista_estudiante.obtenerNombreL(Indice_Estudiante), Administrador.lista_estudiante.obtenerCorreoL(Indice_Estudiante), Administrador.lista_estudiante.obtenerCreditoL(Indice_Estudiante), Administrador.lista_estudiante.obtenerContraseñaL(Indice_Estudiante), semestre);
        ListaSemestre estudiantesemestres = Administrador.lista_estudiante.obtenerSemestreL(Indice_Estudiante);
        System.out.println(Administrador.lista_estudiante.obtenerCarneL(Indice_Estudiante) + " - " + Administrador.lista_estudiante.obtenerNombreL(Indice_Estudiante));
        estudiantesemestres.imprimir();
        //Administrador.lista_estudiante.imprimir();
    }//GEN-LAST:event_basignarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int Indice_Estudiante = Administrador.lista_estudiante.obtenerIndice(Login.UsuEstudiante);
        Administrador.lista_estudiante.modificar(Indice_Estudiante, Administrador.lista_estudiante.obtenerCarneL(Indice_Estudiante), Administrador.lista_estudiante.obtenerCuiL(Indice_Estudiante), Administrador.lista_estudiante.obtenerNombreL(Indice_Estudiante), Administrador.lista_estudiante.obtenerCorreoL(Indice_Estudiante), Administrador.lista_estudiante.obtenerCreditoL(Indice_Estudiante), Administrador.lista_estudiante.obtenerContraseñaL(Indice_Estudiante), semestre);
        ListaSemestre estudiantesemestres = Administrador.lista_estudiante.obtenerSemestreL(Indice_Estudiante);
        System.out.println(Administrador.lista_estudiante.obtenerCarneL(Indice_Estudiante) + " - " + Administrador.lista_estudiante.obtenerNombreL(Indice_Estudiante));
        estudiantesemestres.imprimir();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Estudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Estudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Estudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Estudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Estudiante().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton basignar;
    private javax.swing.JButton bsalir;
    private javax.swing.JComboBox<String> cbcurso;
    private javax.swing.JComboBox<String> cbsemestre;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblusuario;
    // End of variables declaration//GEN-END:variables
}
